eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    loadbalancer:
      rule: random
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
        - id: vehicle-service
          uri: lb://VEHICLE-SERVICE
          predicates:
            - Path=/vehicles/**
        - id: parking-service
          uri: lb://PARKING-SERVICE
          predicates:
            - Path=/parkings/**
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payments/**